export interface ReportMetadata {
	organizationLines?: string[];
	department: string;
	subdepartment: string;
	reportType: string;
	reportProfile?:
		'nir' | 'coursework' | 'lab' | 'vkr-bachelor' | 'vkr-master';
	degree: string;
	semester: number;
	specialtyCode: string;
	specialtyName: string;
	profileName: string;
	studentName: string;
	groupNumber: string;
	topic: string;
	topicPrefix?: string;
	supervisorName: string;
	supervisorTitle: string;
	supervisorRole?: string;
	normControllerName?: string;
	normControllerTitle?: string;
	vkrApprovalName?: string;
	vkrOrderDate?: string;
	vkrOrderNumber?: string;
	vkrInitialData?: string;
	vkrQuestions?: string;
	vkrAssignmentDate?: string;
	studentShortName?: string;
	universitySupervisorShortName?: string;
	organizationSupervisorName?: string;
	organizationSupervisorTitle?: string;
	organizationSupervisorRole?: string;
	practiceKind?: string;
	practiceType?: string;
	practiceStartDate?: string;
	practiceEndDate?: string;
	submissionDate?: string;
	defenseDate?: string;
	gradeLine?: string;
	grade?: string;
	city: string;
	year: number;
	hideSignatures?: boolean;
}
